[package]
name = "debose"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rusqlite = "0.28.0"

regex = "1.7.1"
rand = "0.8"